services:
  api-gateway:
    build: .
    command: uvicorn main:application --host 0.0.0.0 --port 8000
    ports:
    - "8000:8000"
    depends_on:
    - redpanda

  
  # ── PostgreSQL ──────────────────────────────────────────────────────────────
  postgres:
    image: postgres:16-alpine
    container_name: auth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.2
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
      - "9644:9644"
    volumes:
      - redpanda-data:/var/lib/redpanda/data

  console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "8081:8080"
    environment:
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      - redpanda
  topic-init:
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.2
    depends_on:
      - redpanda
    entrypoint: |
      /bin/sh -c '
      set -e

      echo "waiting for cluster..."
      until rpk cluster info --brokers redpanda:9092 >/dev/null 2>&1; do
        sleep 2
      done

      echo "creating topics..."
      rpk topic create orders --brokers redpanda:9092 --partitions 3
      rpk topic create payments --brokers redpanda:9092 --partitions 3
      rpk topic create notifications --brokers redpanda:9092 --partitions 1

      echo "verifying..."
      rpk topic list --brokers redpanda:9092
      '

  auth-service:
    build: .
    command: uvicorn main:application --host 0.0.0.0 --port 8001
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8001
      DATABASE_URL: postgresql://postgres:secret@postgres:5432/auth_db
      REDPANDA_BROKERS: redpanda:9092
    ports:
      - "8001:8001"
    depends_on:
      - redpanda
      - postgres
volumes:
  redpanda-data:
  postgres_data:
