import os
import json
import logging
from dotenv import load_dotenv
from google import genai
from google.genai import types
from taiga_client import TaigaClient

load_dotenv()

GEMINI_MODEL=os.getenv("GEMINI_MODEL")
client= genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
logger = logging.getLogger("discord_bot.agent")

taiga= TaigaClient(os.getenv("TAIGA_URL"),os.getenv("TAIGA_USER"),os.getenv("TAIGA_PASS"))

TOOLS= types.Tool(function_declarations = [

    # tool for create an item in the project
    types.FunctionDeclaration(
        name= "create_item",
        description= "Create a new issue, task, user story or epic in Taiga.",
        parameters= {
            "type":"object",
            "properties": {
                "resource":{
                    "type":"string",
                    "enum": ["issues","tasks","userstories","epics"],
                },
                "subject": {"type": "string"},
                "description": {"type": "string"},
            },
            "required":["resource", "subject"],
        },
    ),
])

def execute_tool(name,args,project_id):
    logger.info("Executing tool %s with args=%s project_id=%s", name, args, project_id)
    if name == "create_item":
        payload={"project":project_id, "subject": args["subject"],"description":args.get("description","")}
        return taiga.create(args["resource"],payload)
    raise ValueError(f"Unknown tool: {name}")


def run_agent(user_message, project_id):
    logger.info("Starting agent run with message=%r project_id=%s", user_message, project_id)
    contents=[types.Content(role="user", parts=[types.Part.from_text(text=user_message)])]

    config= types.GenerateContentConfig(
        tools=[TOOLS],
        automatic_function_calling= types.AutomaticFunctionCallingConfig(disable=True),
        system_instruction=(
            "You are a Taiga project assisstant. Use the available tools to fulfil the user's request."
        ),
    )

    for _ in range(5):
        logger.info("Calling Gemini model %s", GEMINI_MODEL)
        response=client.models.generate_content(
            model=GEMINI_MODEL, contents=contents, config=config,
        )

        logger.info(
            "Gemini response received: text_present=%s function_call_count=%s",
            bool(getattr(response, "text", None)),
            len(getattr(response, "function_calls", []) or []),
        )

        if not response.function_calls:
            final_text = response.text or "No response was generated by Gemini."
            logger.info("Returning plain Gemini response")
            return final_text
        
        contents.append(response.candidates[0].content)

        function_response_parts = []
        for fc in response.function_calls:
            name, args = fc.name, fc.args

            try:
                result = execute_tool(name, args, project_id)
            except Exception as e:
                logger.exception("Tool execution failed for %s", name)
                result = {"error": str(e)}

            logger.info("Tool %s result: %s", name, result)

            function_response_parts.append(
                types.Part.from_function_response(name=name, response={"result": result})
            )

        contents.append(types.Content(role = "tool", parts= function_response_parts))
    
    logger.warning("Agent loop exhausted without completion")
    return "Sorry, I couldn't complete that after several attempts."


