// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ApiAuthEmailSendOtpSendOtpHandlerData, ApiAuthEmailSendOtpSendOtpHandlerErrors, ApiAuthEmailSendOtpSendOtpHandlerResponses, ApiAuthEmailVerifyOtpVerifyOtpHandlerData, ApiAuthEmailVerifyOtpVerifyOtpHandlerErrors, ApiAuthEmailVerifyOtpVerifyOtpHandlerResponses, ApiAuthSocialProviderSocialAuthHandlerData, ApiAuthSocialProviderSocialAuthHandlerErrors, ApiAuthSocialProviderSocialAuthHandlerResponses, ApiHealthHealthCheckData, ApiHealthHealthCheckResponses, ApiPaymentsPlansPlansHandlerData, ApiPaymentsPlansPlansHandlerResponses, ApiPaymentsSetupIntentSetupIntentHandlerData, ApiPaymentsSetupIntentSetupIntentHandlerErrors, ApiPaymentsSetupIntentSetupIntentHandlerResponses, ApiPaymentsWebhookWebhookHandlerData, ApiPaymentsWebhookWebhookHandlerResponses, AuthProviderCallbackSocialCallbackData, AuthProviderCallbackSocialCallbackErrors, AuthProviderCallbackSocialCallbackResponses, AuthProviderLoginSocialLoginData, AuthProviderLoginSocialLoginErrors, AuthProviderLoginSocialLoginResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * HealthCheck
 */
export const apiHealthHealthCheck = <ThrowOnError extends boolean = false>(options?: Options<ApiHealthHealthCheckData, ThrowOnError>): RequestResult<ApiHealthHealthCheckResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ApiHealthHealthCheckResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/health',
    ...options
});

/**
 * SendOtpHandler
 */
export const apiAuthEmailSendOtpSendOtpHandler = <ThrowOnError extends boolean = false>(options: Options<ApiAuthEmailSendOtpSendOtpHandlerData, ThrowOnError>): RequestResult<ApiAuthEmailSendOtpSendOtpHandlerResponses, ApiAuthEmailSendOtpSendOtpHandlerErrors, ThrowOnError> => (options.client ?? client).post<ApiAuthEmailSendOtpSendOtpHandlerResponses, ApiAuthEmailSendOtpSendOtpHandlerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/email/send-otp',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * VerifyOtpHandler
 */
export const apiAuthEmailVerifyOtpVerifyOtpHandler = <ThrowOnError extends boolean = false>(options: Options<ApiAuthEmailVerifyOtpVerifyOtpHandlerData, ThrowOnError>): RequestResult<ApiAuthEmailVerifyOtpVerifyOtpHandlerResponses, ApiAuthEmailVerifyOtpVerifyOtpHandlerErrors, ThrowOnError> => (options.client ?? client).post<ApiAuthEmailVerifyOtpVerifyOtpHandlerResponses, ApiAuthEmailVerifyOtpVerifyOtpHandlerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/email/verify-otp',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * SocialAuthHandler
 */
export const apiAuthSocialProviderSocialAuthHandler = <ThrowOnError extends boolean = false>(options: Options<ApiAuthSocialProviderSocialAuthHandlerData, ThrowOnError>): RequestResult<ApiAuthSocialProviderSocialAuthHandlerResponses, ApiAuthSocialProviderSocialAuthHandlerErrors, ThrowOnError> => (options.client ?? client).post<ApiAuthSocialProviderSocialAuthHandlerResponses, ApiAuthSocialProviderSocialAuthHandlerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/social/{provider}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * PlansHandler
 */
export const apiPaymentsPlansPlansHandler = <ThrowOnError extends boolean = false>(options?: Options<ApiPaymentsPlansPlansHandlerData, ThrowOnError>): RequestResult<ApiPaymentsPlansPlansHandlerResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ApiPaymentsPlansPlansHandlerResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/payments/plans',
    ...options
});

/**
 * SetupIntentHandler
 */
export const apiPaymentsSetupIntentSetupIntentHandler = <ThrowOnError extends boolean = false>(options: Options<ApiPaymentsSetupIntentSetupIntentHandlerData, ThrowOnError>): RequestResult<ApiPaymentsSetupIntentSetupIntentHandlerResponses, ApiPaymentsSetupIntentSetupIntentHandlerErrors, ThrowOnError> => (options.client ?? client).post<ApiPaymentsSetupIntentSetupIntentHandlerResponses, ApiPaymentsSetupIntentSetupIntentHandlerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/payments/setup-intent',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * WebhookHandler
 */
export const apiPaymentsWebhookWebhookHandler = <ThrowOnError extends boolean = false>(options?: Options<ApiPaymentsWebhookWebhookHandlerData, ThrowOnError>): RequestResult<ApiPaymentsWebhookWebhookHandlerResponses, unknown, ThrowOnError> => (options?.client ?? client).post<ApiPaymentsWebhookWebhookHandlerResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/payments/webhook',
    ...options
});

/**
 * SocialLogin
 */
export const authProviderLoginSocialLogin = <ThrowOnError extends boolean = false>(options: Options<AuthProviderLoginSocialLoginData, ThrowOnError>): RequestResult<AuthProviderLoginSocialLoginResponses, AuthProviderLoginSocialLoginErrors, ThrowOnError> => (options.client ?? client).get<AuthProviderLoginSocialLoginResponses, AuthProviderLoginSocialLoginErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/{provider}/login',
    ...options
});

/**
 * SocialCallback
 */
export const authProviderCallbackSocialCallback = <ThrowOnError extends boolean = false>(options: Options<AuthProviderCallbackSocialCallbackData, ThrowOnError>): RequestResult<AuthProviderCallbackSocialCallbackResponses, AuthProviderCallbackSocialCallbackErrors, ThrowOnError> => (options.client ?? client).get<AuthProviderCallbackSocialCallbackResponses, AuthProviderCallbackSocialCallbackErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/{provider}/callback',
    ...options
});
