// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * PlanResponse
 */
export type PlanResponse = {
    id: string;
    name: string;
    description: string;
    price_monthly: number;
    price_yearly: number;
    price_id_monthly: string;
    price_id_yearly: string;
    features: Array<string>;
    badge?: string | null;
    highlighted?: boolean;
};

/**
 * PlansResponse
 */
export type PlansResponse = {
    plans: Array<PlanResponse>;
};

/**
 * SendOTPRequest
 */
export type SendOtpRequest = {
    email: string;
};

/**
 * SendOTPResponse
 */
export type SendOtpResponse = {
    message: string;
    expires_in_seconds: number;
};

/**
 * SetupIntentRequest
 */
export type SetupIntentRequest = {
    name: string;
    email: string;
    price_id: string;
};

/**
 * SetupIntentResponse
 */
export type SetupIntentResponse = {
    client_secret: string;
    setup_intent_id: string;
    customer_id?: string | null;
};

/**
 * SocialAuthRequest
 */
export type SocialAuthRequest = {
    code: string;
    redirect_uri: string;
};

/**
 * VerifyOTPRequest
 */
export type VerifyOtpRequest = {
    email: string;
    otp: string;
};

export type ApiHealthHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type ApiHealthHealthCheckResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: unknown;
    };
};

export type ApiHealthHealthCheckResponse = ApiHealthHealthCheckResponses[keyof ApiHealthHealthCheckResponses];

export type ApiAuthEmailSendOtpSendOtpHandlerData = {
    body: SendOtpRequest;
    path?: never;
    query?: never;
    url: '/api/auth/email/send-otp';
};

export type ApiAuthEmailSendOtpSendOtpHandlerErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiAuthEmailSendOtpSendOtpHandlerError = ApiAuthEmailSendOtpSendOtpHandlerErrors[keyof ApiAuthEmailSendOtpSendOtpHandlerErrors];

export type ApiAuthEmailSendOtpSendOtpHandlerResponses = {
    /**
     * Document created, URL follows
     */
    201: SendOtpResponse;
};

export type ApiAuthEmailSendOtpSendOtpHandlerResponse = ApiAuthEmailSendOtpSendOtpHandlerResponses[keyof ApiAuthEmailSendOtpSendOtpHandlerResponses];

export type ApiAuthEmailVerifyOtpVerifyOtpHandlerData = {
    body: VerifyOtpRequest;
    path?: never;
    query?: never;
    url: '/api/auth/email/verify-otp';
};

export type ApiAuthEmailVerifyOtpVerifyOtpHandlerErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiAuthEmailVerifyOtpVerifyOtpHandlerError = ApiAuthEmailVerifyOtpVerifyOtpHandlerErrors[keyof ApiAuthEmailVerifyOtpVerifyOtpHandlerErrors];

export type ApiAuthEmailVerifyOtpVerifyOtpHandlerResponses = {
    /**
     * Document created, URL follows
     */
    201: {
        [key: string]: unknown;
    };
};

export type ApiAuthEmailVerifyOtpVerifyOtpHandlerResponse = ApiAuthEmailVerifyOtpVerifyOtpHandlerResponses[keyof ApiAuthEmailVerifyOtpVerifyOtpHandlerResponses];

export type ApiAuthSocialProviderSocialAuthHandlerData = {
    body: SocialAuthRequest;
    path: {
        provider: string;
    };
    query?: never;
    url: '/api/auth/social/{provider}';
};

export type ApiAuthSocialProviderSocialAuthHandlerErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiAuthSocialProviderSocialAuthHandlerError = ApiAuthSocialProviderSocialAuthHandlerErrors[keyof ApiAuthSocialProviderSocialAuthHandlerErrors];

export type ApiAuthSocialProviderSocialAuthHandlerResponses = {
    /**
     * Document created, URL follows
     */
    201: {
        [key: string]: unknown;
    };
};

export type ApiAuthSocialProviderSocialAuthHandlerResponse = ApiAuthSocialProviderSocialAuthHandlerResponses[keyof ApiAuthSocialProviderSocialAuthHandlerResponses];

export type ApiPaymentsPlansPlansHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/payments/plans';
};

export type ApiPaymentsPlansPlansHandlerResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PlansResponse;
};

export type ApiPaymentsPlansPlansHandlerResponse = ApiPaymentsPlansPlansHandlerResponses[keyof ApiPaymentsPlansPlansHandlerResponses];

export type ApiPaymentsSetupIntentSetupIntentHandlerData = {
    body: SetupIntentRequest;
    path?: never;
    query?: never;
    url: '/api/payments/setup-intent';
};

export type ApiPaymentsSetupIntentSetupIntentHandlerErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiPaymentsSetupIntentSetupIntentHandlerError = ApiPaymentsSetupIntentSetupIntentHandlerErrors[keyof ApiPaymentsSetupIntentSetupIntentHandlerErrors];

export type ApiPaymentsSetupIntentSetupIntentHandlerResponses = {
    /**
     * Document created, URL follows
     */
    201: SetupIntentResponse;
};

export type ApiPaymentsSetupIntentSetupIntentHandlerResponse = ApiPaymentsSetupIntentSetupIntentHandlerResponses[keyof ApiPaymentsSetupIntentSetupIntentHandlerResponses];

export type ApiPaymentsWebhookWebhookHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/payments/webhook';
};

export type ApiPaymentsWebhookWebhookHandlerResponses = {
    /**
     * Document created, URL follows
     */
    201: {
        [key: string]: unknown;
    };
};

export type ApiPaymentsWebhookWebhookHandlerResponse = ApiPaymentsWebhookWebhookHandlerResponses[keyof ApiPaymentsWebhookWebhookHandlerResponses];

export type AuthProviderLoginSocialLoginData = {
    body?: never;
    path: {
        provider: string;
    };
    query?: never;
    url: '/auth/{provider}/login';
};

export type AuthProviderLoginSocialLoginErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type AuthProviderLoginSocialLoginError = AuthProviderLoginSocialLoginErrors[keyof AuthProviderLoginSocialLoginErrors];

export type AuthProviderLoginSocialLoginResponses = {
    /**
     * Redirect Response
     */
    200: unknown;
};

export type AuthProviderCallbackSocialCallbackData = {
    body?: never;
    path: {
        provider: string;
    };
    query?: never;
    url: '/auth/{provider}/callback';
};

export type AuthProviderCallbackSocialCallbackErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type AuthProviderCallbackSocialCallbackError = AuthProviderCallbackSocialCallbackErrors[keyof AuthProviderCallbackSocialCallbackErrors];

export type AuthProviderCallbackSocialCallbackResponses = {
    /**
     * Redirect Response
     */
    200: unknown;
};
