export const weeks = ["W1", "W2", "W3", "W4", "W5", "W6", "W7", "W8", "W9", "W10"];
export const adoption = [31, 36, 42, 47, 53, 58, 63, 67, 70, 73];

export const projects = [
  {
    id: "proj-01",
    name: "Carrier rate-limit fix",
    status: "at-risk",
    health: 62,
    lead: "Leo Martins",
    team: ["LM", "NA", "PK"],
    sprint: "Sprint 24",
    tasksDone: 14,
    tasksTotal: 22,
    lastActivity: "2h ago",
    scopeChange: "+30%",
    velocity: "↓ 12%",
  },
  {
    id: "proj-02",
    name: "Payments audit pipeline",
    status: "on-track",
    health: 94,
    lead: "Priya Kapoor",
    team: ["PK", "JD", "AR"],
    sprint: "Sprint 24",
    tasksDone: 18,
    tasksTotal: 19,
    lastActivity: "12m ago",
    scopeChange: "+2%",
    velocity: "↑ 8%",
  },
  {
    id: "proj-03",
    name: "Mobile redesign v3",
    status: "on-track",
    health: 81,
    lead: "Nora Albir",
    team: ["NA", "TK", "MS"],
    sprint: "Sprint 23",
    tasksDone: 31,
    tasksTotal: 40,
    lastActivity: "41m ago",
    scopeChange: "+5%",
    velocity: "→ 0%",
  },
  {
    id: "proj-04",
    name: "Leadership digest automation",
    status: "on-track",
    health: 97,
    lead: "Bot",
    team: ["Bot"],
    sprint: "Sprint 24",
    tasksDone: 8,
    tasksTotal: 8,
    lastActivity: "Mon",
    scopeChange: "0%",
    velocity: "↑ 4%",
  },
  {
    id: "proj-05",
    name: "Platform eng migration",
    status: "at-risk",
    health: 58,
    lead: "Tom Kowalski",
    team: ["TK", "JD", "LM"],
    sprint: "Sprint 23",
    tasksDone: 9,
    tasksTotal: 16,
    lastActivity: "3h ago",
    scopeChange: "+18%",
    velocity: "↓ 22%",
  },
  {
    id: "proj-06",
    name: "QA regression suite",
    status: "completed",
    health: 100,
    lead: "Nora Albir",
    team: ["NA", "MS"],
    sprint: "Sprint 22",
    tasksDone: 24,
    tasksTotal: 24,
    lastActivity: "Yesterday",
    scopeChange: "0%",
    velocity: "↑ 15%",
  },
];

export const users = [
  {
    id: "u-01",
    name: "Leo Martins",
    initials: "LM",
    role: "Staff Engineer",
    team: "Platform",
    activeProjects: 3,
    tasksClosedThisWeek: 12,
    velocityTrend: "+8%",
    trustRate: 91,
    hoursSaved: 34,
    status: "online",
    lastActive: "Now",
    workload: 88,
  },
  {
    id: "u-02",
    name: "Priya Kapoor",
    initials: "PK",
    role: "Engineering Manager",
    team: "Platform",
    activeProjects: 4,
    tasksClosedThisWeek: 8,
    velocityTrend: "+15%",
    trustRate: 96,
    hoursSaved: 42,
    status: "online",
    lastActive: "Now",
    workload: 94,
  },
  {
    id: "u-03",
    name: "Nora Albir",
    initials: "NA",
    role: "Senior Engineer",
    team: "Mobile",
    activeProjects: 2,
    tasksClosedThisWeek: 9,
    velocityTrend: "+3%",
    trustRate: 87,
    hoursSaved: 28,
    status: "away",
    lastActive: "41m ago",
    workload: 76,
  },
  {
    id: "u-04",
    name: "Tom Kowalski",
    initials: "TK",
    role: "Engineer",
    team: "Mobile",
    activeProjects: 2,
    tasksClosedThisWeek: 5,
    velocityTrend: "-4%",
    trustRate: 78,
    hoursSaved: 18,
    status: "offline",
    lastActive: "3h ago",
    workload: 64,
  },
  {
    id: "u-05",
    name: "Maya Singh",
    initials: "MS",
    role: "QA Lead",
    team: "QA",
    activeProjects: 2,
    tasksClosedThisWeek: 15,
    velocityTrend: "+11%",
    trustRate: 94,
    hoursSaved: 24,
    status: "online",
    lastActive: "Now",
    workload: 48,
  },
  {
    id: "u-06",
    name: "James Doyle",
    initials: "JD",
    role: "Engineer",
    team: "Platform",
    activeProjects: 2,
    tasksClosedThisWeek: 7,
    velocityTrend: "+2%",
    trustRate: 82,
    hoursSaved: 21,
    status: "away",
    lastActive: "1h ago",
    workload: 72,
  },
  {
    id: "u-07",
    name: "Ava Reyes",
    initials: "AR",
    role: "Designer",
    team: "Design",
    activeProjects: 1,
    tasksClosedThisWeek: 6,
    velocityTrend: "+5%",
    trustRate: 89,
    hoursSaved: 15,
    status: "offline",
    lastActive: "5h ago",
    workload: 62,
  },
];

export const feed = [
  {
    id: 1,
    actor: "Leo Martins",
    initials: "LM",
    isBot: false,
    text: "confirmed the payments audit plan — 4 tasks created in Jira",
    time: "2 minutes ago",
  },
  {
    id: 2,
    actor: "Bot",
    initials: "Bot",
    isBot: true,
    text: "proposed a plan for \"Carrier rate-limit fix\" in #platform-eng",
    time: "14 minutes ago",
  },
  {
    id: 3,
    actor: "Nora Albir",
    initials: "NA",
    isBot: false,
    text: "marked the QA regression epic complete",
    time: "41 minutes ago",
  },
  {
    id: 4,
    actor: "Bot",
    initials: "Bot",
    isBot: true,
    text: "flagged the mobile redesign as at risk — scope grew 30% this week",
    time: "1 hour ago",
  },
  {
    id: 5,
    actor: "Priya Kapoor",
    initials: "PK",
    isBot: false,
    text: "closed Sprint 23 review — 87% of stories delivered on time",
    time: "2 hours ago",
  },
];

export const capacity = [
  { team: "Platform team", percent: 94, color: "var(--color-destructive)" },
  { team: "Mobile team", percent: 81, color: "var(--color-primary)" },
  { team: "Design", percent: 62, color: "var(--color-primary)" },
  { team: "QA", percent: 48, color: "var(--color-muted-foreground)" },
];

export const reportData = {
  projectVelocity: [
    { week: "W1", platform: 42, mobile: 38, design: 28, qa: 35 },
    { week: "W2", platform: 45, mobile: 40, design: 30, qa: 38 },
    { week: "W3", platform: 43, mobile: 44, design: 32, qa: 36 },
    { week: "W4", platform: 48, mobile: 41, design: 35, qa: 40 },
    { week: "W5", platform: 50, mobile: 43, design: 33, qa: 42 },
    { week: "W6", platform: 47, mobile: 46, design: 36, qa: 44 },
    { week: "W7", platform: 52, mobile: 48, design: 38, qa: 45 },
    { week: "W8", platform: 54, mobile: 50, design: 40, qa: 43 },
    { week: "W9", platform: 55, mobile: 49, design: 42, qa: 47 },
    { week: "W10", platform: 58, mobile: 52, design: 44, qa: 48 },
  ],
  userContributions: [
    { name: "Leo M", commits: 142, reviews: 38, bugs: 4, features: 12 },
    { name: "Priya K", commits: 89, reviews: 52, bugs: 2, features: 8 },
    { name: "Nora A", commits: 156, reviews: 29, bugs: 7, features: 15 },
    { name: "Tom K", commits: 98, reviews: 21, bugs: 9, features: 10 },
    { name: "Maya S", commits: 45, reviews: 18, bugs: 22, features: 3 },
    { name: "James D", commits: 112, reviews: 31, bugs: 5, features: 11 },
    { name: "Ava R", commits: 67, reviews: 44, bugs: 1, features: 6 },
  ],
};
