// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { apiAuthEmailSendOtpSendOtpHandler, apiAuthEmailVerifyOtpVerifyOtpHandler, apiAuthSocialProviderSocialAuthHandler, apiHealthHealthCheck, apiPaymentsPlansPlansHandler, apiPaymentsSetupIntentSetupIntentHandler, apiPaymentsWebhookWebhookHandler, authProviderCallbackSocialCallback, authProviderLoginSocialLogin, type Options } from '../sdk.gen';
import type { ApiAuthEmailSendOtpSendOtpHandlerData, ApiAuthEmailSendOtpSendOtpHandlerError, ApiAuthEmailSendOtpSendOtpHandlerResponse, ApiAuthEmailVerifyOtpVerifyOtpHandlerData, ApiAuthEmailVerifyOtpVerifyOtpHandlerError, ApiAuthEmailVerifyOtpVerifyOtpHandlerResponse, ApiAuthSocialProviderSocialAuthHandlerData, ApiAuthSocialProviderSocialAuthHandlerError, ApiAuthSocialProviderSocialAuthHandlerResponse, ApiHealthHealthCheckData, ApiHealthHealthCheckResponse, ApiPaymentsPlansPlansHandlerData, ApiPaymentsPlansPlansHandlerResponse, ApiPaymentsSetupIntentSetupIntentHandlerData, ApiPaymentsSetupIntentSetupIntentHandlerError, ApiPaymentsSetupIntentSetupIntentHandlerResponse, ApiPaymentsWebhookWebhookHandlerData, ApiPaymentsWebhookWebhookHandlerResponse, AuthProviderCallbackSocialCallbackData, AuthProviderCallbackSocialCallbackError, AuthProviderLoginSocialLoginData, AuthProviderLoginSocialLoginError } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const apiHealthHealthCheckQueryKey = (options?: Options<ApiHealthHealthCheckData>) => createQueryKey('apiHealthHealthCheck', options);

/**
 * HealthCheck
 */
export const apiHealthHealthCheckOptions = (options?: Options<ApiHealthHealthCheckData>) => queryOptions<ApiHealthHealthCheckResponse, DefaultError, ApiHealthHealthCheckResponse, ReturnType<typeof apiHealthHealthCheckQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await apiHealthHealthCheck({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: apiHealthHealthCheckQueryKey(options)
});

/**
 * SendOtpHandler
 */
export const apiAuthEmailSendOtpSendOtpHandlerMutation = (options?: Partial<Options<ApiAuthEmailSendOtpSendOtpHandlerData>>): UseMutationOptions<ApiAuthEmailSendOtpSendOtpHandlerResponse, ApiAuthEmailSendOtpSendOtpHandlerError, Options<ApiAuthEmailSendOtpSendOtpHandlerData>> => {
    const mutationOptions: UseMutationOptions<ApiAuthEmailSendOtpSendOtpHandlerResponse, ApiAuthEmailSendOtpSendOtpHandlerError, Options<ApiAuthEmailSendOtpSendOtpHandlerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await apiAuthEmailSendOtpSendOtpHandler({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * VerifyOtpHandler
 */
export const apiAuthEmailVerifyOtpVerifyOtpHandlerMutation = (options?: Partial<Options<ApiAuthEmailVerifyOtpVerifyOtpHandlerData>>): UseMutationOptions<ApiAuthEmailVerifyOtpVerifyOtpHandlerResponse, ApiAuthEmailVerifyOtpVerifyOtpHandlerError, Options<ApiAuthEmailVerifyOtpVerifyOtpHandlerData>> => {
    const mutationOptions: UseMutationOptions<ApiAuthEmailVerifyOtpVerifyOtpHandlerResponse, ApiAuthEmailVerifyOtpVerifyOtpHandlerError, Options<ApiAuthEmailVerifyOtpVerifyOtpHandlerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await apiAuthEmailVerifyOtpVerifyOtpHandler({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * SocialAuthHandler
 */
export const apiAuthSocialProviderSocialAuthHandlerMutation = (options?: Partial<Options<ApiAuthSocialProviderSocialAuthHandlerData>>): UseMutationOptions<ApiAuthSocialProviderSocialAuthHandlerResponse, ApiAuthSocialProviderSocialAuthHandlerError, Options<ApiAuthSocialProviderSocialAuthHandlerData>> => {
    const mutationOptions: UseMutationOptions<ApiAuthSocialProviderSocialAuthHandlerResponse, ApiAuthSocialProviderSocialAuthHandlerError, Options<ApiAuthSocialProviderSocialAuthHandlerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await apiAuthSocialProviderSocialAuthHandler({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const apiPaymentsPlansPlansHandlerQueryKey = (options?: Options<ApiPaymentsPlansPlansHandlerData>) => createQueryKey('apiPaymentsPlansPlansHandler', options);

/**
 * PlansHandler
 */
export const apiPaymentsPlansPlansHandlerOptions = (options?: Options<ApiPaymentsPlansPlansHandlerData>) => queryOptions<ApiPaymentsPlansPlansHandlerResponse, DefaultError, ApiPaymentsPlansPlansHandlerResponse, ReturnType<typeof apiPaymentsPlansPlansHandlerQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await apiPaymentsPlansPlansHandler({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: apiPaymentsPlansPlansHandlerQueryKey(options)
});

/**
 * SetupIntentHandler
 */
export const apiPaymentsSetupIntentSetupIntentHandlerMutation = (options?: Partial<Options<ApiPaymentsSetupIntentSetupIntentHandlerData>>): UseMutationOptions<ApiPaymentsSetupIntentSetupIntentHandlerResponse, ApiPaymentsSetupIntentSetupIntentHandlerError, Options<ApiPaymentsSetupIntentSetupIntentHandlerData>> => {
    const mutationOptions: UseMutationOptions<ApiPaymentsSetupIntentSetupIntentHandlerResponse, ApiPaymentsSetupIntentSetupIntentHandlerError, Options<ApiPaymentsSetupIntentSetupIntentHandlerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await apiPaymentsSetupIntentSetupIntentHandler({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * WebhookHandler
 */
export const apiPaymentsWebhookWebhookHandlerMutation = (options?: Partial<Options<ApiPaymentsWebhookWebhookHandlerData>>): UseMutationOptions<ApiPaymentsWebhookWebhookHandlerResponse, DefaultError, Options<ApiPaymentsWebhookWebhookHandlerData>> => {
    const mutationOptions: UseMutationOptions<ApiPaymentsWebhookWebhookHandlerResponse, DefaultError, Options<ApiPaymentsWebhookWebhookHandlerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await apiPaymentsWebhookWebhookHandler({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const authProviderLoginSocialLoginQueryKey = (options: Options<AuthProviderLoginSocialLoginData>) => createQueryKey('authProviderLoginSocialLogin', options);

/**
 * SocialLogin
 */
export const authProviderLoginSocialLoginOptions = (options: Options<AuthProviderLoginSocialLoginData>) => queryOptions<unknown, AuthProviderLoginSocialLoginError, unknown, ReturnType<typeof authProviderLoginSocialLoginQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await authProviderLoginSocialLogin({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: authProviderLoginSocialLoginQueryKey(options)
});

export const authProviderCallbackSocialCallbackQueryKey = (options: Options<AuthProviderCallbackSocialCallbackData>) => createQueryKey('authProviderCallbackSocialCallback', options);

/**
 * SocialCallback
 */
export const authProviderCallbackSocialCallbackOptions = (options: Options<AuthProviderCallbackSocialCallbackData>) => queryOptions<unknown, AuthProviderCallbackSocialCallbackError, unknown, ReturnType<typeof authProviderCallbackSocialCallbackQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await authProviderCallbackSocialCallback({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: authProviderCallbackSocialCallbackQueryKey(options)
});
